### ISSUE TITLE
CSV output contains duplicate items

### ISSUE THREAD

**Issue by eight04** [knewjade/solution-finder#3]
Input:
https://harddrop.com/fumen/?v115@pgD8EeE8DeF8CeG8CeG8DeH8AeC8JeAgWwAt088AQx?78AwTsTASY1TAyUPRAyp78AwDhTASYMeDUPNXEuoo2AN588?AwUMlE

Output:
https://gist.github.com/eight04/14d39d66df8cd7db7176e55cd2add492

You can see that L2 and L4 are the same. Is this a bug?

**Comment by knewjade** [comment]
Thank you for contacting me.
It looks like a bug to me too. I will investigate and fix it. However, I think it will take some time, sorry.

**Comment by eight04** [comment]
Is it because that there are 2 T in the pattern?

**Comment by knewjade** [comment]
@eight04 As a result of my investigation, it's not a bug.
in your input, the pattern used 8 pieces was entered for the field required 5 pieces. As a result, the distinction was made where it wasn't shown. (TZJLIT**OS**, TZJLIT**SO**)
When more pieces are inputted than necessary, a warning is shown in `percent`, but it isn't in `path` now. so I will add it. thank you.
